package com.dotstudioz.services;

public class Constants {
    public final static String BASE_URL = "https://api.myspotlight.tv";
    public final static String KEY_ACCESS_TOKEN = "x-access-token";
    public final static String KEY_CLIENT_TOKEN = "x-client-token";
    public final static String VALUE_ACCESS_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YWIxNjAwNTk3ZjgxNTAxNGIzNTc4OTEiLCJleHBpcmVzIjoxNTI5ODI1ODMzMDY3LCJjb250ZXh0Ijp7Im5hbWUiOiJSZXZyeSIsInN1YmRvbWFpbiI6InJldnJ5IiwicmVhZF9vbmx5IjpmYWxzZX19.rc-KX2Q1_dncTf2lL2gs4UXCzAromQ-Ogo8TGCLDQBc";
    public final static String VALUE_CLIENT_TOKEN = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiI1YWIxNjAwNTk3ZjgxNTAxNGIzNTc4OTEiLCJleHBpcmVzIjoxNTI3MjUzNzM2MDc3LCJjb250ZXh0Ijp7ImF2YXRhciI6Imh0dHA6Ly9jZG4uZG90c3R1ZGlvcHJvLmNvbS9hdmF0YXJzLzU5NDc3YmZmNmE2MzY3YzgwNWFmZTJiNzU0MmM0ZjU0OTdmODE1N2M0NzdiMjNjNi5wbmciLCJpZCI6IjU0MmM0ZjU0OTdmODE1N2M0NzdiMjNjNiIsImZpcnN0X25hbWUiOiJNb2hzaW4iLCJsYXN0X25hbWUiOiJTaGFpa2gifX0.PxA2i7R_XWin6aGd786_bHU2dJP1cdnPLrPufwYwPyE";
}
